title = 'swizzard dot pizza'
baseURL = 'https://swizzard.pizza/'

defaultContentLanguage = 'en'
languageCode = 'en-us'

enableGitInfo = true
enableEmoji = true

theme = ['docura']

[markup]
highlight.noClasses = false
defaultMarkdownHandler = 'goldmark'
[markup.goldmark]
[markup.goldmark.extensions]
GFM = true
