description = "Sam Raker's Website"

author = 'Sam Raker'
authorURL = 'https://swizzard.pizza/'
authorEmail = 'me@swizzard.pizza'

currentYear = 2024
projectStartYear = 2023

githubURL = 'https://github.com/swizzard'
blueskyURL = 'https://bsky.app/profile/swizzard.pizza'
cohostURL = 'https://cohost.org/swizzard'
