description = "Sam Raker's Website"

author = 'Sam Raker'
authorURL = 'https://your-site.com/'

currentYear = 2023

githubURL = 'https://github.com/swizzard'
blueskyURL = 'https://bsky.app/profile/swizzard.pizza'
cohostURL = 'https://cohost.org/swizzard'
